services:
  - type: web
    name: smartview-app
    env: node
    buildCommand: npm install && npm run build && npx drizzle-kit push --verbose
    startCommand: node render-startup.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: smartview-db
          property: connectionString
    autoDeploy: false
    healthCheckPath: /api/health

databases:
  - name: smartview-db
    databaseName: smartview
    user: smartview_user